### ISSUE TITLE
Home Page header not update's after signin

### ISSUE THREAD

**Issue by brst-dev** [GordonLesti/Lesti_Fpc#187]
I am facing a issue in my home page header section. When i used to login , after login the homepage ( login and signup links are not changing to account and signout.) . I think this is due to FPC. 
In all other pages the links are changing according to situation. 
After disabling FPC , its working fine .

**Comment by GordonLesti** [comment]
Hello @brst-dev 
this can have different reasons.
* maybe your links are not part of the block `top.links` that should be a lazy block by default. If so please read this [post](http://gordonlesti.com/what-are-lazy-and-dynamic-blocks-in-lesti-fpc/)
* the `refresh_action` `customer_account_login` is not dispatched after login, maybe because of a ajax-login?
