### ISSUE TITLE
Filter cached

### ISSUE THREAD

**Issue by tsaong** [GordonLesti/Lesti_Fpc#253]
Hello,

I have a confilct with your extension and filters on category page with your LESTI FPC extension for magento community.

The thing is when users click on filters, they are automatically cached. So if another user comes on the website filters are already selected!

Is there a way to add a code in the configuration to not cache filters?

I dont really know if I am clear!! :-(
Let me know
Best
Greg

**Comment by GordonLesti** [comment]
Hello @tsaong 
some information would be useful:
* Magento version?
* FPC version?
* Is `Add Layered Navigation Attributes To Uri Params` in the configs of FPC enabled?

**Comment by tsaong** [comment]
Hi GordonLesti

• Magento ver. 1.9.1.0
• Lesti_Fpc 	1.3.6
• What do you mean by Add Layered Navigation Attributes To Uri Params ?

I have tried to add some code as "___SID=U&ajaxcatalog" in Miss Uri Params
But as I dont understand a word I have no idée of what I am doing!!!

Thank you for your help

**Comment by GordonLesti** [comment]
Since version 1.4 FPC has the option [Add Layered Navigation Attributes To Uri Params](https://github.com/GordonLesti/Lesti_Fpc/blob/1.4.6/app/code/community/Lesti/Fpc/etc/system.xml#L81). An other option would be to use [Uri Params](http://gordonlesti.com/what-are-uri-params-in-lesti-fpc/). I hope this will help you.

**Comment by tsaong** [comment]
Awesome, I have update the version and it seems working quite fine!!
Thank you a lot

**Comment by GordonLesti** [comment]
You are welcome.
