### ISSUE TITLE
Howto disable caching of cookies?

### ISSUE THREAD

**Issue by eddetollenaer** [GordonLesti/Lesti_Fpc#271]
First of all, this module helps us a lot in speeding up our shop. Great work.

There's one thing though that I cannot get fixed. It seems that cookies are not being read well.

I created a module that shows a fancybox popup with a country and currency selector if the user visits the shop for the first time. When this popup is shown a cookie 'popup-shown' is set. 
The next time the user visits the site, I check if this cookie is set. If so, the fancybox popup is not shown again.

This works with Lesti_Fpc disabled, but with Lesti_Fpc enabled the popup gets shown all the time.

The code for this is:

```
    jQuery(document).ready(function() {
        var check_cookie = "<?php echo Mage::getModel('core/cookie')->get('popup-shown'); ?>";

        if(!check_cookie) {
            <?php Mage::getModel('core/cookie')->set('popup-shown', 'true', 60*60*24*300); // 300 days?>
            beginCurrencyForm();
        }
    });
```
Could you please help me how to get this to work in combination with your FPC module? For now I have to disable the FPC completely unfortunately.

Thank you in advance,
Ed

**Comment by eddetollenaer** [comment]
I think found the solution. Turned out I had to add my custom block as Dynamic block and after that refresh the FPC cache.

Refreshing the cache did the trick.

**Comment by GordonLesti** [comment]
Hello @eddetollenaer 
just a small thing, FPC is never caching cookies. FPC is just caching HTML content. I guess the code from above is part of one of your templates. You you should put that code into a [dynamic or lazy block](https://gordonlesti.com/what-are-lazy-and-dynamic-blocks-in-lesti-fpc/), so that is fresh executed for every customer and not cached by FPC.

_Just a few small hints to your code:_
* _It is often better to put logical code into a block class instead of a template_
* _A Javascript_ `if` _-statements in a PHP template does not prevent the execution from PHP code. The PHP code_ `Mage::getModel('core/cookie')->set('popup-shown', 'true', 60*60*24*300);` _ of your template will be executed with every rendering of template_

**Comment by eddetollenaer** [comment]
Thank you for the explanation. Adding my block to the dynamic blocks in combination with refreshing the FPC cache was the solution.
