### ISSUE TITLE
Problem loading images after flushing cache

### ISSUE THREAD

**Issue by ReindDooyeweerd** [GordonLesti/Lesti_Fpc#46]
With the latest version of the module i experience an issue with the product images when viewing an category.

After flushing the cache all images dissapwar on the website. Flushing/refreshing it again, restarting nginx, php-fpm, redis won't help to solve the issue. Only way to get the images back is disable the FPC cache, flush everything and then turn the FPC back on however the problem will appear next time the cache has been flushed.

Anyone else having this issue or am i the only one?

**Comment by eddetollenaer** [comment]
I have the exact same problem. Without Lesti, the images appear fine.
When enabling Lesti, the images are fine at first, but later on the start disappearing and show broken links. 
They reappear if you disable Lesti.

We use Lesti with REDIS cache. No idea why this is not working.

**Comment by GordonLesti** [comment]
Hello @eddetollenaer 
we can reopen this issue if you want to. I need some more information:
* Magento version
* FPC version.
* URI of an example image that is broken (with FPC enabled)
* URI of the same image that is not broken (with FPC disabled)

**Comment by eddetollenaer** [comment]
Dear Gordon,
Thank you for your reaction.

Magento version is: 1.9.2.4
FPC version is: 1.4.5

The url is: https://www.truckparts1919.com/media/catalog/product/cache/1/small_image/295x/040ec09b1e35df139433887a97daa66f/v/b/vbg-actuator-5038816.jpg

Now we disabled Lesti because itś the live environment, so it is visible. If we enable Lesti, it is visible at first, but the link gets broken after a while. Not sure how much time it takes before it gets broken. This is the case for every image in the image cache of Magento.

Do you need more information?

**Comment by eddetollenaer** [comment]
I dove a little deeper in the issue.
It seems that the cached image (https://www.truckparts1919.com/media/catalog/product/cache/1/small_image/295x/040ec09b1e35df139433887a97daa66f/v/b/vbg-actuator-5038816.jpg) disappears even without Lesti_Fpc. If you call the cached image url directly, it will not show an image anymore after a while.

But...
After calling the product list page on which this image is shown (https://www.truckparts1919.com/accessories-towbars/?p=1), the image is shown on the product list page and the cached image seems to be regenerated. After that calling the cached image directly is possible again.

Theoretically could this explain why the image is not shown when Lesti_Fpc is running. For some reason cached images might be cleared from the server until they get regenerated. I never heard of this before and I might be wrong. The next time the image is not visible I will check if the image is physically not present in the server folder.

**Comment by GordonLesti** [comment]
Hello @eddetollenaer 
I guess the cache backend (Redis) is not relevant in this case. I guess this can also happen with an other cache backend (file, memcached, ...).
Can it be that you have an importer that flushes the image "cache"?

**Comment by eddetollenaer** [comment]
Hi @GordonLesti ,
You are right!!! After importing products our custom importer flushes the image cache because old images were shown after each import. I think this is the main reason why this issue occurs on our server. I totally forgot that I made this a couple of months ago :cry: 
I have to see if I can rebuild the importer so the image cache is not cleared but rebuild.

**Comment by GordonLesti** [comment]
@eddetollenaer Maybe you can flush the FPC at the same time?

**Comment by eddetollenaer** [comment]
Yes, I can, but the importer runs every 15 minutes so the caching has no function anymore then. I will write a module that rebuilds the image cache for the imported images very time a product gets updated. We had to flush the image cache because using the default Magento image import API did not show the altered images, but shows the old images. I think I will be able to fix this problem. Thank you so much for your time!

**Comment by GordonLesti** [comment]
@eddetollenaer you are welcome

**Comment by eddetollenaer** [comment]
I wrote a module that rebuilds the cached images for a product that was updated with the images API form Magento and now this works flawless :)
